spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3309/sfg_dev
    username: sfg_dev_user
    password: guru
    platform: mysql
  jpa:
    hibernate: 
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true 
    
# Below should be uncommented when we want to create our DB schema for this application. Once schema is up & running, we can comment it back    
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql